### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined on shallow component

### ISSUE THREAD

**Issue by joffotron** [producthunt/chai-enzyme#114]
Hi,

I'm using 0.5.2 and I have: 

``` js
// In my setup.js ......
var chai = require("chai");

var chaiEnzyme = require('chai-enzyme');
chai.use(chaiEnzyme()); 

// In my test ......
import React from 'react';
import {shallow} from 'enzyme';
import { MyForm } from './my-form';

describe("\<MyForm>", () => {
  let wrapper = null;

  beforeEach(() => {
    const props = {
      csrf: {
        param: 'cool_csrf',
        token: '123456789'
      },
    };
    wrapper = shallow(<MyForm {...props}/>);
  });

  it("sets the CSRF token", () => {
    var field = wrapper.find('input[name="cool_csrf"]');
    expect(field.html()).to.contain('value="123456789"');
    expect(field).to.have.value('123456789');
  });
});
```

The _first_ assertion works fine (i.e the it finds the input field okay), but I then get:

```
TypeError: Cannot read property 'value' of undefined
      at value (node_modules/chai-enzyme/build/assertions/value.js:13:23)
      at .<anonymous> (node_modules/chai-enzyme/build/ChaiWrapper.js:193:19)
      at ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at .<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:21)
      at ctx.(anonymous function) [as value] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at Context.<anonymous> (test/build/app/components/rails-form/webpack::29:1)
```

**Comment by ayrton** [comment]
I don't see any issues with the code above, I tried to reproduce the issue with the following code on master:

```js
import React from 'react';
import {shallow} from 'enzyme';

const MyForm = ({ csrf }) => <form><input name={csrf.param} value={csrf.token} /></form>

describe("MyForm", () => {
  let wrapper = null;

  beforeEach(() => {
    const props = {
      csrf: {
        param: 'cool_csrf',
        token: '123456789'
      },
    };
    wrapper = shallow(<MyForm {...props}/>);
  });

  it("sets the CSRF token", () => {
    var field = wrapper.find('input[name="cool_csrf"]');
    expect(field.html()).to.contain('value="123456789"');
    expect(field).to.have.value('123456789');
  });
});
```

this returns me:

```
$ NODE_ENV=test npme mocha test/foo.test.js


  MyForm
    ✓ sets the CSRF token


  1 passing (132ms)
```

Closing this, feel free to re-open if you can give more context.
