### ISSUE TITLE
`Contain` assertion passes when given non-node

### ISSUE THREAD

**Issue by IanVS** [producthunt/chai-enzyme#18]
It seems that the `contain` assertion does not check for the correct type of argument.  For example, this will pass:

```js
const wrapper = shallow(<Fixture />) 

expect(wrapper).to.contain("FooPony")
```

And:

```js
const wrapper = shallow(<Fixture />) 

expect(wrapper).to.not.contain("FooPony")
```

will fail with:

```
TypeError: obj.indexOf is not a function
      at Assertion.include (node_modules/chai/lib/chai/core/assertions.js:221:45)
      at Assertion.assert (node_modules/chai/lib/chai/utils/addChainableMethod.js:83:49)
```

**Comment by IanVS** [comment]
Hm, it actually seems this could be an upstream issue, since enzyme itself is exhibiting the same behavior.

**Comment by IanVS** [comment]
https://github.com/airbnb/enzyme/issues/145 submitted to Enzyme.
