### ISSUE TITLE
Getting "Cannot read property 'hasDescendants' of undefined"

### ISSUE THREAD

**Issue by msaspence** [producthunt/chai-enzyme#30]
```
at Assertion.descendants (/Users/matthew.spence/Projects/tripapplite/node_modules/chai-enzyme/build/assertions/descendants.js:13:22)
      at Assertion.<anonymous> (/Users/matthew.spence/Projects/tripapplite/node_modules/chai-enzyme/build/index.js:139:19)
      at Assertion.ctx.(anonymous function) [as descendants] (/Users/matthew.spence/Projects/tripapplite/node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.<anonymous> (/Users/matthew.spence/Projects/tripapplite/app/assets/javascripts/tripapp_specs_mocha.js:218703:53)
      at callFn (/Users/matthew.spence/Projects/tripapplite/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/Users/matthew.spence/Projects/tripapplite/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/Users/matthew.spence/Projects/tripapplite/node_modules/mocha/lib/runner.js:373:10)
      at /Users/matthew.spence/Projects/tripapplite/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/matthew.spence/Projects/tripapplite/node_modules/mocha/lib/runner.js:298:14)
      at /Users/matthew.spence/Projects/tripapplite/node_modules/mocha/lib/runner.js:308:7
```

**Comment by ljharb** [comment]
Can you provide a bit of the code you used to get this error, and which versions of chai-enzyme and enzyme and chai and mocha you are using?

**Comment by ayrton** [comment]
I'm closing this because it's not clear what's causing this, or what versions are being used, feel free to re-open when there is a more detailed bug report.

**Comment by msaspence** [comment]
Sorry, might have time to look at this today, will reopen with more info when I can
