### ISSUE TITLE
to.have assertions fail with 'TypeError: Cannot read property '<prop_name>' of undefined'

### ISSUE THREAD

**Issue by lisss** [producthunt/chai-enzyme#88]
I'm trying to use `to.have.text` assertion for my component test but it fails for me with `TypeError: Cannot read property 'text' of undefined`
To demonstrate, I've tried an example from your docs:
```
import * as React from 'react';
import * as chai from 'chai';
import chaiEnzyme from 'chai-enzyme';
import { shallow } from 'enzyme';

chai.use(chaiEnzyme());

class Fixture extends React.Component<{}, {}> {
  render () {
    return (
      <div id='root'>
        <span id='child'>Test</span>
      </div>
    );
  }
}

const wrapper = shallow(<Fixture />);
chai.expect(wrapper.find('#child')).to.have.text('Test');
```

Here's the full stacktrace:
```
var actual = wrapper.text();
                      ^

TypeError: Cannot read property 'text' of undefined
    at Assertion.text (/Users/liss/Work/Dev/Git/denali/node_modules/chai-enzyme/build/assertions/text.js:15:23)
    at Assertion.<anonymous> (/Users/liss/Work/Dev/Git/denali/node_modules/chai-enzyme/build/ChaiWrapper.js:193:19)
    at Assertion.ctx.(anonymous function) [as text] (/Users/liss/Work/Dev/Git/denali/dist_test/client/main.js:47531:26)
    at Object.<anonymous> (/Users/liss/Work/Dev/Git/denali/dist_test/client/main.js:43219:46)
    at __webpack_require__ (/Users/liss/Work/Dev/Git/denali/dist_test/client/main.js:21:30)
    at Object.module.exports._typeof (/Users/liss/Work/Dev/Git/denali/dist_test/client/main.js:43248:2)
    at __webpack_require__ (/Users/liss/Work/Dev/Git/denali/dist_test/client/main.js:21:30)
    at Object.<anonymous> (/Users/liss/Work/Dev/Git/denali/dist_test/client/main.js:74:19)
    at __webpack_require__ (/Users/liss/Work/Dev/Git/denali/dist_test/client/main.js:21:30)
    at /Users/liss/Work/Dev/Git/denali/dist_test/client/main.js:41:18
    at Object.<anonymous> (/Users/liss/Work/Dev/Git/denali/dist_test/client/main.js:44:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/liss/Work/Dev/Git/denali/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/liss/Work/Dev/Git/denali/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/liss/Work/Dev/Git/denali/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/liss/Work/Dev/Git/denali/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

It looks like applicable to all `to.have` assertions
chai-enzyme version is 0.5.0

**Comment by lisss** [comment]
It turned out to be a caching issue... :anguished:

**Comment by MaximeHeckel** [comment]
How did you manage to fix this?

**Comment by lisss** [comment]
@MaximeHeckel, not sure what exactly was causing the issue but after a lot of time spent debugging I've just completely cleared up build directory, rebuilt the project and it started working 😄 
But if it doesn't help, there might be also possibility that you have multiple enzyme instances (one imported by your tests and another imported by chai-enzyme)
