### ISSUE TITLE
Shallow `contain` fails

### ISSUE THREAD

**Issue by evandavis** [producthunt/chai-enzyme#92]
The [documentation for `contain`](https://github.com/producthunt/chai-enzyme#containnode) states that I can assert a shallow wrapper contains a node, but this SSCE fails:

```javascript
import React, {Component} from 'react';

function ChildComponent() {
  return <div className="child" />;
}

class MyComponent extends Component {
  render() {
    return (
      <div>
        <ChildComponent />
      </div>
    );
  }
}

describe('My Component', function () {
  it('renders the child', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper).to.contain(<ChildComponent />);
  });

  it('finds the child', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper.find(ChildComponent)).to.have.length(1);
  });
});
```

`it('renders the child')` throws the following error:
```
AssertionError: expected { Object (root, unrendered, ...) } to have a property '$$typeof'
```

but `it('finds the child')` passes.

(Note that I have `expect` and `shallow` available as globals in my Mocha test env.)

**Are the docs wrong** or am I using this method incorrectly?

**Comment by ayrton** [comment]
I'm not entirely sure what is wrong with the code you've posted. I just ran your test code on master with the following results:

```sh
$ NODE_ENV=test npme mocha test/foo.test.js


  My Component
    ✓ renders the child
    ✓ finds the child


  2 passing (647ms)
```

**Comment by evandavis** [comment]
@ayrton can you post your testfile? (What is `npme`?)

I'm using: 
```
chai-enzyme@0.5.0
enzyme@2.4.1
mocha@3.0.0
```
and very much still getting this error.

**Comment by evandavis** [comment]
This is interesting...

```javascript
describe.only('My Component', function () {
  it('works in enzyme', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper.contains(<ChildComponent />)).to.equal(true);
  });

  it('but not in chai-enzyme', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper).to.contain(<ChildComponent />);
  });
});
```

results in

```
My Component
    ✓ works in enzyme
    1) but not in chai-enzyme
```

😞

**Comment by ayrton** [comment]
This is my test file (`test/foo.test.js`):

```js
import {shallow} from 'enzyme';

function ChildComponent() {
  return <div className="child" />;
}

class MyComponent extends React.Component {
  render() {
    return (
      <div>
        <ChildComponent />
      </div>
    );
  }
}

describe('My Component', function () {
  it('renders the child', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper).to.not.contain(<ChildComponent />);
  });

  it('finds the child', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper.find(ChildComponent)).to.have.length(1);
  });
});
```

`npme` is an alias I have on my machine:

```sh
$ NODE_ENV=test npme mocha test/foo.test.js
```

translates to:

```sh
$ NODE_ENV=test ./node_modules/.bin/mocha test/foo.test.js
```

**Comment by evandavis** [comment]
You are testing the OPPOSITE of my assertion; you have `expect(wrapper).to.not.contain(<ChildComponent />)`.

**Comment by ayrton** [comment]
@evandavis sorry that was a 'typo' - I wanted to check later one that the tests failed negated. 

These all succeed: 

```js
import {shallow} from 'enzyme';

function ChildComponent() {
  return <div className="child" />;
}

class MyComponent extends React.Component {
  render() {
    return (
      <div>
        <ChildComponent />
      </div>
    );
  }
}

describe('My Component', function () {
  it('renders the child', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper).to.contain(<ChildComponent />);
  });

  it('finds the child', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper.find(ChildComponent)).to.have.length(1);
  });
});
```

**Comment by evandavis** [comment]
And you have the same versions of the dependencies that I have?

**Comment by ayrton** [comment]
This is an exact copy of your test code at the beginning of the thread except for the added

```js
import {shallow} from 'enzyme';
```

and missing (b/c of global): 

```js
import React, {Component} from 'react';
```

with the following dependencies:

```
chai-enzyme@master
enzyme@2.4.1
mocha@3.0.0
```

**Comment by evandavis** [comment]
Welp, OK, I guess I just can't use this package.

**Comment by ayrton** [comment]
@evandavis try removing your `node_modules` directory and `npm install`. My guess is that there's some outdate dependency. If not can you isolate this issue in something re-producable so I can dig in.

**Comment by evandavis** [comment]
After re-installing my `node_modules`, I've simplified the example down to:

```javascript
import React from 'react';
import {shallow} from 'enzyme';
import {expect} from 'chai';

function MyComponent() {
  return (
    <div>
      <div />
    </div>
  );
}

describe.only('My Component', function () {
  it('works in enzyme', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper.contains(<div />)).to.equal(true);
  });

  it('but not in chai-enzyme', () => {
    const wrapper = shallow(<MyComponent />);
    expect(wrapper).to.contain(<div />);
  });
});
```

which I run with
```
./node_modules/mocha/bin/mocha --require babel-core/register foo.test.js
```
and I get the same results. The `.to.contain` test fails.

**Comment by ayrton** [comment]
The problem is that you didn't [set up chai-enzyme](https://github.com/producthunt/chai-enzyme#setup) properly. I've created a demo repo to reproduce this.

__Before:__
https://github.com/ayrton/chai-enzyme-issue-92/commit/1286f417df8c60887711149224587402a4665f2c

```sh
$ npm test

> chai-enzyme-issue-92@1.0.0 test /Users/adc/Developer/ayrton/chai-enzyme-issue-92
> mocha --require babel-core/register foo.test.js



  My Component
    ✓ works in enzyme
    1) but not in chai-enzyme


  1 passing (744ms)
  1 failing

  1) My Component but not in chai-enzyme:
     AssertionError: expected { Object (root, unrendered, ...) } to have a property '$$typeof'
      at Assertion.include (node_modules/chai/lib/chai/core/assertions.js:221:47)
      at Assertion.assert (node_modules/chai/lib/chai/utils/addChainableMethod.js:84:49)
      at Context.<anonymous> (foo.test.js:21:24)



npm ERR! Test failed.  See above for more details.
```

__After:__
https://github.com/ayrton/chai-enzyme-issue-92/commit/5511d692ae18e987cb6f22f8438052baf49f2700

```sh
$ npm test

> chai-enzyme-issue-92@1.0.0 test /Users/adc/Developer/ayrton/chai-enzyme-issue-92
> mocha foo.test.js



  My Component
    ✓ works in enzyme
    ✓ but not in chai-enzyme


  2 passing (795ms)
```
